### ISSUE TITLE
Ceramics breaks EnderIO's JEI plugin

### ISSUE THREAD

**Issue by bondgb** [KnightMiner/Ceramics#2]
Disabling Ceramics solves the issue.

[Client thread/ERROR] [JEI/]: Failed to register mod plugin: class crazypants.enderio.jei.JeiPlugin
java.lang.NullPointerException
	at knightminer.ceramics.items.ItemClayBucket.doesBreak(ItemClayBucket.java:237) ~[ItemClayBucket.class:?]
	at knightminer.ceramics.library.FluidClayBucketWrapper.setFluid(FluidClayBucketWrapper.java:28) ~[FluidClayBucketWrapper.class:?]
	at net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper.drain(FluidBucketWrapper.java:171) ~[FluidBucketWrapper.class:?]
	at crazypants.enderio.jei.TankRecipeCategory.register(TankRecipeCategory.java:115) ~[TankRecipeCategory.class:?]
	at crazypants.enderio.jei.JeiPlugin.register(JeiPlugin.java:47) ~[JeiPlugin.class:?]
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:169) [ProxyCommonClient.class:?]
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142) [ProxyCommonClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_759_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraft.world.World.func_72838_d(World.java:1129) [aid.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196) [bln.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by KnightMiner** [comment]
Hmm, looks like someone is registering a fluid without a block. I'll have to add a check for that.

**Comment by HenryLoenwind** [comment]
That would be Liquid XP, I'd say.

**Comment by KnightMiner** [comment]
Actually, that would be a better check
